### ISSUE TITLE
PN5180 freeze when detecting/ removing a card

### ISSUE THREAD

**Issue by s0301132** [playfultechnology/arduino-rfid-PN5180#1]
@alastaira Thank you for your code, after testing with my PN5180 and esp32 I found that sometimes when I put/ remove the RFID card on PN5180 it will freeze and refuse any detection, I open a debug console with some log below.

When it's normal (Put the card and remove it):
```
 *  Executing task in folder PN5180 ESP32: platformio device monitor --environment heltec_wifi_kit_32_v2 

--- Terminal on /dev/cu.usbserial-0001 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H

Read IRQ-Status register...
Reading register 0x02...
Sending SPI frame: '04 02'
Receiving SPI frame...
Received: 07 40 00 00'
Register value=0x00004007
IRQ-Status=0x00004007
Reading register 0x13...
Sending SPI frame: '04 13'
Receiving SPI frame...
Received: 0A 00 00 00'
Register value=0x0000000A
RX-Status=0000000A, len=10
Reading Data (len=10)...
Sending SPI frame: '0A 00'
Receiving SPI frame...
Received: 00 00 C4 14 94 B5 50 01 04 E0'
Data read: 00 00 C4 14 94 B5 50 01 04 E0 
Read=00:00:C4:14:94:B5:50:01:04:E0
Read IRQ-Status register...
Reading register 0x02...
Sending SPI frame: '04 02'
Receiving SPI frame...
Received: 07 40 00 00'
Register value=0x00004007
IRQ-Status=0x00004007
Clear IRQ-Status with mask=x00004007
Write Register 0x03, value (LSB first)=0x07400000
Sending SPI frame: '00 03 07 40 00 00'
Response flags: 00, Data Storage Format ID: 00, UID: 00:00:0000B59414C4
New Card Detected on Reader 0... C4 14 94 B5 50 1 4 E0 
Get Inventory...
Issue Command 0x01...
Send data (len=3): 26 01 00
Write Register 0x00 with AND mask (LSB first)=0xF8FFFFFF
Sending SPI frame: '02 00 F8 FF FF FF'
Write Register 0x00 with OR mask (LSB first)=0x03000000
Sending SPI frame: '01 00 03 00 00 00'
Get Transceive state...
Reading register 0x1D...
Sending SPI frame: '04 1D'
Receiving SPI frame...
Received: 4E 00 06 01'
Register value=0x0106004E
TRANSCEIVE_STATE=0x01
Sending SPI frame: '09 00 26 01 00'
Read IRQ-Status register...
Reading register 0x02...
Sending SPI frame: '04 02'
Receiving SPI frame...
Received: 07 40 00 00'
Register value=0x00004007
IRQ-Status=0x00004007
Reading register 0x13...
Sending SPI frame: '04 13'
Receiving SPI frame...
Received: 0A 00 00 00'
Register value=0x0000000A
RX-Status=0000000A, len=10
Reading Data (len=10)...
Sending SPI frame: '0A 00'
Receiving SPI frame...
Received: 00 00 C4 14 94 B5 50 01 04 E0'
Data read: 00 00 C4 14 94 B5 50 01 04 E0 
Read=00:00:C4:14:94:B5:50:01:04:E0
```

When freeze:
```
Read IRQ-Status register...
Reading register 0x02...
Sending SPI frame: '04 02'
Receiving SPI frame...
Received: 06 40 00 00'
Register value=0x00004006
IRQ-Status=0x00004006
Read IRQ-Status register...
Reading register 0x02...
Sending SPI frame: '04 02'
Receiving SPI frame...
Received: 06 40 00 00'
Register value=0x00004006
IRQ-Status=0x00004006
Read IRQ-Status register...
Reading register 0x02...
Sending SPI frame: '04 02'
Receiving SPI frame...
Received: 06 40 00 00'
Register value=0x00004006
IRQ-Status=0x00004006
```

Hopefully my log can help.

**Comment by alastaira** [comment]
Thanks for the report - yes, I believe the chip sometimes hangs if it gets corrupted data (i.e. when the card is moved out of range mid-read). I'll try to look into a more robust solution but, in the meantime, please try adding the following at the top of loop() so that the chip gets reset and the field re-activated before each read:

```
    nfc.reset();
    nfc.setupRF();
```

**Comment by s0301132** [comment]
Hi @alastaira thanks for the response, I try the reset code in loop and still having the error, after some investigation I found that the problem may cause by `PN5180ISO15693.cpp` from line 511:

```
ISO15693ErrorCode PN5180ISO15693::issueISO15693Command(uint8_t *cmd, uint8_t cmdLen, uint8_t **resultPtr) {
#ifdef DEBUG
  PN5180DEBUG(F("Issue Command 0x"));
  PN5180DEBUG(formatHex(cmd[1]));
  PN5180DEBUG("...\n");
#endif

  sendData(cmd, cmdLen);
  delay(10);

  uint32_t irqR = getIRQStatus();
  if (0 == (irqR & RX_SOF_DET_IRQ_STAT)) {
	return EC_NO_CARD;
  }
  
  while(!(irqR & RX_IRQ_STAT)) {
	delay(1);
	irqR = getIRQStatus();
  }
```

The exception ```while(!(irqR & RX_IRQ_STAT))``` only get IRQ status and loop forever when data is corrupted, may need to reset something in here and get the correct IRQ to make it work again, thanks @alastaira

**Comment by s0301132** [comment]
For now I just put ```ESP.restart();``` when that exception happened but not ideal.

**Comment by boharii** [comment]
> For now I just put `ESP.restart();` when that exception happened but not ideal.

Hello, where did you put this line of code? I think i'm having the exact same issue as you with the card freezing upon data corruption.

**Comment by s0301132** [comment]
@boharii in `PN5180ISO15693.cpp`

The function `ISO15693ErrorCode PN5180ISO15693::issueISO15693Command(uint8_t *cmd, uint8_t cmdLen, uint8_t **resultPtr)`

```
ISO15693ErrorCode PN5180ISO15693::issueISO15693Command(uint8_t *cmd, uint8_t cmdLen, uint8_t **resultPtr)
{
#ifdef DEBUG
  PN5180DEBUG(F("Issue Command 0x"));
  PN5180DEBUG(formatHex(cmd[1]));
  PN5180DEBUG("...\n");
#endif

  sendData(cmd, cmdLen);
  delay(10);

  uint32_t irqR = getIRQStatus();
  if (0 == (irqR & RX_SOF_DET_IRQ_STAT))
  {
    return EC_NO_CARD;
  }

  /*while (0 == (irqR & RX_IRQ_STAT))
  {
    delay(10);
    irqR = getIRQStatus();
  }*/
```

Comment the `while (0 == (irqR & RX_IRQ_STAT))` part and the program will not freeze when data is corrupted.

**Comment by boharii** [comment]
Thank you, this worked for me!

**Comment by alastaira** [comment]
Thanks for the input! You're correct - the use of a blocking delay() to wait for RX_IRQ_STAT to be set should be changed. 
Its purpose is to ensure that RF reception from the tag has been completed before allowing the code to read any values from the IRQ_STATUS register (i.e. to ensure you don't receive partial reads). 

One solution to prevent the code hanging would be to set a timeout within which the code waits for the reception bit to be set (in the same way that a timeout is set for the RF field to be activated in [lines 489-494 of PN5180.cpp](https://github.com/playfultechnology/PN5180-Library/blob/e64468d65906c207bdaf900a1645615c71f3d5ca/PN5180.cpp#L489-L494)). However, on balance, I'm not even sure if it's required; if you want to ensure the read was complete before acting on the results, you can always call getIRQStatus() and explicitly check the value of the RX_IRQ_STAT bit before deciding to proceed anyway. 

I'll make the necessary changes in the source file. Cheers!
